//Created Date: 04/03/2018
//Created By: Ashish Tiwari
//Usage: add Application session key in this file.
//IMP NOTE: Never add the key in between of enum, it is prefrable that You add in the bottom enum.
//Copyright:Violet InfoSystems Pvt.Ltd
export enum enAppSession {
    UserAccountID,
    id,
    UserCode,
    Salutation,
    full_name,
    FirstName,
    MiddleName,
    LastName,
    ScreenName,
    Email,
    Address,
    CountyID,
    StateID,
    CityID,
    CountryName,
    StateName,
    CityName,
    MobileNumber,
    PhoneNumber,
    TimeZoneID,
    UserPhoto,
    Gender,
    UserType,
    InternetAccess,
    ActiveDays,
    UCMMCode,
    isManager,
    UserPassWord,
    LastLoginDate,
    currentUser,
    hasLoggedIn,
    hasSeenTutorial,
    defaultLanguage,
    hasManager,
    UserMasters,
    domainID,
    apiurl,
    apibaseURL,
    apiSecretKey,
    apiId,
    DomainObject,
    remember,
    username,
    PassWord,
    DateFormatID,
    languageMaster,
    timeZoneMaster,
    domainUrl,
    domainProtoCol,
    userModule,
    trainingUserRole,
    playerId,
    firsttimeLogin,
    oldcount,
    menuLogo,
    isDeviceInfoSet,    
    tpLogoUrl,
    thirdPartyName,
    DateFormat
}


